### ISSUE TITLE
error when attempting MySQL connection.

### ISSUE THREAD

**Issue by davidleebooth** [eccentricdevotion/GameModeInventories#8]
Hello, trying to swap over to mysql from sqlite.
Here is whats coming back from console:

[22:40:26] [Server thread/ERROR]: Error occurred while enabling GameModeInventories v3.3 (Is it up to date?)
java.lang.NoClassDefFoundError: me/eccentric_nz/org/slf4j/LoggerFactory
	at me.eccentric_nz.com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at me.eccentric_nz.gamemodeinventories.database.GameModeInventoriesConnectionPool.<init>(GameModeInventoriesConnectionPool.java:41) ~[?:?]
	at me.eccentric_nz.gamemodeinventories.GameModeInventories.loadDatabase(GameModeInventories.java:148) ~[?:?]
	at me.eccentric_nz.gamemodeinventories.GameModeInventories.onEnable(GameModeInventories.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: me.eccentric_nz.org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

**Comment by eccentricdevotion** [comment]
Try build 135 or higher from here: http://tardisjenkins.duckdns.org:8080/job/GameModeInventories/
